### ISSUE TITLE
无法生成报告

### ISSUE THREAD

**Issue by thanksdanny** [TesterlifeRaymond/BeautifulReport#1]
你好啊，请问这个是python3的才能用么

**Comment by TesterlifeRaymond** [comment]
是的， 这是一个py3版本的测试报告

**Comment by liuwei19831117** [comment]
During handling of the above exception, another exception occurred: Traceback (most recent call last):   File "C:\Users\chanjing\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 58, in testPartExecutor    yield   File "C:\Users\chanjing\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 600, in run    testMethod()   File "C:\Users\chanjing\AppData\Local\Programs\Python\Python35\lib\site-packages\BeautifulReport\BeautifulReport.py", line 423, in __wrap    sys.exit(0) SystemExit: 0
--

请大神抽空看看，这是什么错误，还有就是希望能把失败用例，拆成error,fail两类统计，谢谢！

**Comment by TesterlifeRaymond** [comment]
emmm.... 目前来说现在的配置是和java版本的页面保持的统一, 没有单独做处理, 也就是error和fail拆分开, 这个后续看实际情况如果确实必要, 更新一次
