### ISSUE TITLE
测试case里返回的内容包含了html语法导致测试报告格式乱了

### ISSUE THREAD

**Issue by chenfei5201213** [TesterlifeRaymond/BeautifulReport#11]
![image](https://user-images.githubusercontent.com/8575520/38985086-f8e3ddfe-43fa-11e8-8542-d8238e1cecf4.png)

出现原因：我们的产品请求头错误（token过期等原因导致），会直接返回html内容。我case设计的是失败的case，将所有消息都打印出来，所以就出现了如图错误

**Comment by flybaozi** [comment]
其实抛出所有异常的话感觉并不是一个合理的方案。其实可以考虑存成html文件，然后抛出一个地址可以访问比较直观吧。

**Comment by Lixiang1351** [comment]
把返回html中的“<>”,处理后可避免乱码，replace("<", "").replace(">", "")
