### ISSUE TITLE
路径不对

### ISSUE THREAD

**Issue by Beau-ldd** [TesterlifeRaymond/BeautifulReport#12]
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Python35\\Lib\\site-packages/BeautifulReport/template/template'
这怎么搞，为什么总是报错这个

**Comment by TesterlifeRaymond** [comment]
请问你的环境中是python2和3共存吗? 还是只有一个py3.5 如果只有3.5 建议删除BeautifulReport后 更新最新的代码并放入packages路径

**Comment by flybaozi** [comment]
其实你改一下路径就好了。。 我现在就是放到了项目中
