### ISSUE TITLE
如何实现，想要显示的内容添加到报告中

### ISSUE THREAD

**Issue by sunyingdong** [TesterlifeRaymond/BeautifulReport#13]
try:
            # 启动浏览器，访问首页
            daima_Page.gotoP1()

            # 输入名字
            daima_Page.input_name_text()

            #输入手机号
            daima_Page.input_mobile_text()

            #点选出生日期
            daima_Page.click_date_choose()
            daima_Page.click_birth_choose()

            #点击马上贷款
            daima_Page.click_loan_input()
        except:
            print("需手工验证地址：%s" % url)

实际情况：打开多个URL，输入内容。有的URL无法输入内容跳过执行后，打印出URL地址来。
想要实现：想要把打印出来的URL显示在报告内，我要如何实现呢？

**Comment by TesterlifeRaymond** [comment]
在你的case种 使用print 即可将想要输出的信息展示在html报告中
