### ISSUE TITLE
是否支持python+unittest的assert断言？

### ISSUE THREAD

**Issue by sunyingdong** [TesterlifeRaymond/BeautifulReport#14]
self.assertEqual(input_Page.get_title(), Daima_title)
我尝试了断言，但报告中没有打印内容。
想问，如何写断言才能让断言结果内容显示在报告中

**Comment by TesterlifeRaymond** [comment]
如果想让自己增加的断言内容显示在 report 中, 可以通过 print ("msg")的方式即可, 无需做其他处理
