### ISSUE TITLE
windows上运行会有些问题如图所示：

### ISSUE THREAD

**Issue by 444913387** [TesterlifeRaymond/BeautifulReport#20]
![111](https://user-images.githubusercontent.com/26038792/45410482-60386300-b6a4-11e8-8818-2033a6296ef7.png)
![11111](https://user-images.githubusercontent.com/26038792/45410486-63335380-b6a4-11e8-90ef-455e881e7c49.png)

**Comment by TesterlifeRaymond** [comment]
该问题已修复.
