### ISSUE TITLE
请问下，我用例里面的输出日志为什么不能在窗口显示》

### ISSUE THREAD

**Issue by MrJaven** [TesterlifeRaymond/BeautifulReport#27]
![image](https://user-images.githubusercontent.com/19869332/49919876-1a797980-fee3-11e8-9c5c-e04a233eeeb5.png)

![image](https://user-images.githubusercontent.com/19869332/49919884-21a08780-fee3-11e8-9da9-78ef66c32d27.png)

**Comment by TesterlifeRaymond** [comment]
因为在执行用例的过程中, python的std输出被拦截了, 该部分信息会在报告中有体现
