### ISSUE TITLE
这个提示帮忙看看是怎么发生的

### ISSUE THREAD

**Issue by jjwv** [TesterlifeRaymond/BeautifulReport#3]
![image](https://user-images.githubusercontent.com/29301285/37755047-d6c9c1d4-2dde-11e8-8330-090fc2939130.png)
![image](https://user-images.githubusercontent.com/29301285/37755068-e7f69b1c-2dde-11e8-96b0-87ba9c63d040.png)
![image](https://user-images.githubusercontent.com/29301285/37755080-f1e1ae82-2dde-11e8-971f-71e07485d761.png)

**Comment by jjwv** [comment]
test_tixing003 报告中没有上传截图

**Comment by yangzhijun1** [comment]
我也遇见这个问题了，我的img文件夹里是截图成功了，但是测试报告里，展开后不能显示图片

**Comment by TesterlifeRaymond** [comment]
这个问题主要可能出现的原因, 是在测试过程中, 使用了不同的webdriver 导致多个driver 不同步的情况. 出现无法展示 , 建议在代码中统一使用同一个webdriver的实例, 来进行测试与代码的管理
