### ISSUE TITLE
怎么修改测试报告中的“用例描述”

### ISSUE THREAD

**Issue by lyp0129** [TesterlifeRaymond/BeautifulReport#38]
代码水平有限，请帮小白一个忙。

**Comment by td652720549** [comment]
你好，同小白，我百度了下，是通过每条testcase代码内的注释来完成的，如：“”“我是描述”“”

**Comment by lyp0129** [comment]
好的，这个问题我解决了，还有一个新的问题遇到，方便加一下你的qq交流一下吗？邮件的效率还是有点慢


------------------ 原始邮件 ------------------
发件人: "正体不明"<notifications@github.com>;
发送时间: 2019年9月17日(星期二) 下午4:56
收件人: "TesterlifeRaymond/BeautifulReport"<BeautifulReport@noreply.github.com>;
抄送: "路云鹏"<292596031@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [TesterlifeRaymond/BeautifulReport] 怎么修改测试报告中的“用例描述” (#38)




你好，同小白，我百度了下，是通过每条testcase代码内的注释来完成的，如：“”“我是描述”“”

**Comment by 2362428142-zgb** [comment]
同学我也遇到这个问题了，查了很多资料但是还是不太清楚怎么解决，想问问你当时是怎么解决的
