### ISSUE TITLE
请帮忙看一下为什么没有在报告中显示图片，

### ISSUE THREAD

**Issue by xiaoxiangLiu** [TesterlifeRaymond/BeautifulReport#4]
![beautifulreport](https://user-images.githubusercontent.com/20807131/38077111-6529114c-336a-11e8-84b0-140be5ad6030.png)

**Comment by TesterlifeRaymond** [comment]
在你的代码块中是否定义了save_img的方法?

**Comment by TesterlifeRaymond** [comment]
在使用截图功能的时候, 要在 case 中增加一个方法 save_img
