### ISSUE TITLE
文件里有很多中文，但是没有在文件开头写# coding=utf-8

### ISSUE THREAD

**Issue by DuiduiLi** [TesterlifeRaymond/BeautifulReport#8]
文件里有很多中文，但是没有在文件开头写# coding=utf-8， 会导致出错。
还有方法里行参datas:tuple, 会报错。
其他的方法里有很多-> str或者-> int或者->None这种形式的，也会报错

**Comment by DuiduiLi** [comment]
是的 我的是2.7




| |
国际学院1001 李对对
邮箱：liduidui@126.com
|

签名由 网易邮箱大师 定制

在2018年05月15日 10:20，TesterlifeRaymond 写道：

请问你是2.x版本的吗? Br目前只支持py3.5+

**Comment by TesterlifeRaymond** [comment]
该报告目前只支持3.5+ 没有兼容3.5以下版本
